import React from 'react';

// Define the Props type for the FolderDiagram component
type Props = {
  diagram: string;
};

// Create the FolderDiagram functional component
export const FolderDiagram: React.FC<Props> = ({ diagram }) => {
  /* The purpose of the FolderDiagram component is to render the ASCII diagram of the folder structure that was generated by the useFolderVisualizer hook. The diagram is passed as a prop to the component. The component uses a <pre> element to render the ASCII diagram. The <pre> element preserves the formatting (including spaces and line breaks) of the diagram, which is crucial for maintaining the visual structure.*/
  return <pre>{diagram}</pre>;
};
